name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install UV
      run: pip install uv

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        uv pip sync requirements.txt

    - name: Prepare environment
      run: |
        cp config.example.yaml config.yaml
        cp .env.example .env

    - name: Run tests with coverage
      id: test
      run: |
        source .venv/bin/activate
        pytest --cov=./ --cov-report=xml --cov-report=html
        echo "$?" > test_exit_code.txt  # Store pytest exit code in a file
      continue-on-error: true

    - name: Upload Coverage Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: htmlcov/

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      if: always()

    - name: Fail workflow if tests failed
      run: |
        exit_code=$(cat test_exit_code.txt)  # Retrieve stored exit code
        if [ "$exit_code" -ne 0 ]; then
          echo "Tests failed with exit code $exit_code."
          exit $exit_code
        fi
