name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install UV
      run: pip install uv

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        uv pip sync requirements.txt

    - name: Prepare environment
      run: |
        cp config.example.yaml config.yaml
        cp .env.example .env

    - name: Run tests
      run: pytest --cov=./
      continue-on-error: true

    - name: Upload Coverage Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: htmlcov/

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      if: always()

    - name: Fail if tests failed
      if: failure()
      run: exit 1
